[package]
name = "thunfisch"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2"
rayon = "1.10.0"
num-format = "0.4.4"
arrayvec = "0.7.6"
once_cell = "1.21.3"
assert_cmd = "2.0.17"
predicates = "3.1.3"
