[package]
name = "thunfisch"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
colored = "2"
rayon = "1.10.0"
num-format = "0.4.4"
const_for = "0.1.5"
arrayvec = "0.7.6"
once_cell = "1.21.3"
