# Starts the engine as a lichess bot
# LICHESS_BOT_TOKEN needs to be set as a sys var
# Linux build of this engine needs to exist in the target/release/ folder
# More info: https://github.com/lichess-bot-devs/lichess-bot

version: "3.8"

services:
  lichess-bot:
    image: lichessbotdevs/lichess-bot
    container_name: thunfisch
    volumes:
      - ./config.yml:/lichess-bot/config/config.yml
      - ./target/release/thunfisch:/lichess-bot/thunfisch
    environment:
      LICHESS_BOT_TOKEN: ${LICHESS_BOT_TOKEN}
    restart: unless-stopped
